pipeline {
  agent {
    docker {
      image 'node:18'
    }
  }
  stages {
    // stage('Compile and build') {
    //   steps {
    //     git branch: "master", url: "https://github.com/JhonSanz/pythonandfamily_web"
    //     echo 'clone ok'
    //     sh 'pwd'
    //     dir("pythonandfamily_web") {
    //       echo 'Changed to directory:'
    //       sh 'pwd'
    //       sh 'npm install'
    //       sh 'npm run build'
    //       sh 'ls'
    //     }
    //   }
    // }
    stage('Despliegue a AWS S3') {
      steps {
        script {
            sh 'ls /usr/local/bin/'

            withCredentials([[
              $class: 'AmazonWebServicesCredentialsBinding',
              credentialsId: 'my-aws-credentials',
              accessKeyVariable: 'AWS_ACCESS_KEY_ID',
              secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
            ]]) {
              // s3Upload(file: "pythonandfamily_web/build/index.html", bucket: "test-jenkins-staticwebsite", path: "/")
              sh "/usr/local/bin/aws s3 ls"
            }
        }
      }
    }
  }
}

