pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    dir('files_app') {
                        sh 'echo "CLONE REPO"'
                        git branch: "master", url: "https://github.com/JhonSanz/pythonandfamily_web"
                    }
                }
            }
        }

        stage('Compile Next.js App') {
            agent {
                docker {
                    image 'node:18'
                    reuseNode true
                    args '-u root:root'
                }
            }
            steps {
                script {
                    dir('files_app') {
                        sh 'echo "BUILD STAGE"'
                        sh 'npm install'
                        sh 'npm run build'
                    }
                }
            }
        }

        stage('Upload to S3') {
            steps {
                script {
                    withCredentials([[
                      $class: 'AmazonWebServicesCredentialsBinding',
                      credentialsId: 'my-aws-credentials',
                      accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                      secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                      sh "aws s3 cp files_app/build s3://test-jenkins-staticwebsite/ --recursive"
                    }
                }
            }
        }
    }
}
